version: 3.0.0.{build}

image: Visual Studio 2019

configuration: Release
platform: Any CPU

before_build:
  - dotnet restore

build_script:
  - dotnet build

after_build:
  - dotnet pack src\D2L.Services.Core.Extensions\D2L.Services.Core.Extensions.csproj

test_script:
  - dotnet test test\D2L.Services.Core.Extensions.UnitTests\D2L.Services.Core.Extensions.UnitTests.csproj

dotnet_csproj:
  patch: true
  file: src\**\*.csproj
  version: '{version}'

artifacts:
  - path: src\**\*.nupkg
    name: NuGet

deploy:
  - provider: NuGet
    api_key:
      # D2L.Services.Core.Extensions (Expires: 2019-12-03)
      secure: +21KhruOphAnQKZlSV7L9T50ByQRyTpgf5Ok+3sUV+kVpO4IIwsZM+7a5dt6T0HZ
    on:
      APPVEYOR_REPO_TAG: true
